tap "1password/tap"
tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "surrealdb/tap"
brew "python@3.11"
brew "awscli"
brew "bat"
brew "berkeley-db", link: true
brew "freetype"
brew "fontconfig"
brew "glib"
brew "python@3.9"
brew "chezmoi"
brew "unbound"
brew "gnutls"
brew "colima"
brew "docker"
brew "docker-credential-helper-ecr"
brew "exa"
brew "gdk-pixbuf"
brew "gh"
brew "little-cms2"
brew "gnupg"
brew "gobject-introspection"
brew "gradle"
brew "guile"
brew "harfbuzz"
brew "helix"
brew "htop"
brew "jq"
brew "krb5"
brew "libarchive"
brew "libfido2"
brew "pango"
brew "librsvg"
brew "mas"
brew "openjdk"
brew "maven"
brew "mysql"
brew "n"
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "nghttp2"
brew "node"
brew "openssl@3"
brew "nushell"
brew "tmux"
brew "overmind"
brew "pandoc"
brew "pipx"
brew "postgresql@14"
brew "starship"
brew "swi-prolog"
brew "tere"
brew "trunk"
brew "watchexec"
brew "wget"
brew "wimlib"
brew "wireguard-tools"
brew "yadm"
brew "yarn", link: false
brew "zsh-syntax-highlighting"
brew "stripe/stripe-cli/stripe"
brew "surrealdb/tap/surreal"
cask "1password-cli"
cask "dbeaver-community"
cask "dozer"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "hiddenbar"
cask "maccy"
cask "mactex-no-gui"
cask "postico"
cask "postman"
cask "vlc"
cask "vscodium"
cask "visual-studio-code"
mas "ColorSlurp", id: 1287239339
mas "Dropzone 4", id: 1485052491
mas "Grammarly for Safari", id: 1462114288
mas "Messenger", id: 1480068668
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Table Tool", id: 1122008420
mas "TestFlight", id: 899247664
mas "Todoist", id: 585829637
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
