#!/usr/bin/env bash
#
# Dotfiles installer
# This script is the entry point for both local use and GitHub Codespaces
#
set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

exec "${BASEDIR}/install.sh" "$@"
