require "user.options"
require "user.keymaps"
require "user.plugins"
-- require "user.colorscheme"
require "user.icons"
require "user.completion"
require "user.lsp"
--[[ require "user.lsp-inlay-hints" ]]
require "user.copilot"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comments"
require "user.gitsigns"
-- require "user.nvimtree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
