#!/bin/bash

grieg () {
    

  if [ eval $(op get account | jq -r .uuid) != HZ2SW55B6VHOZETF3FQZLUKNKQ ] 
    then
      eval $(op signin team_zebra) 
  fi
  exp "$(op get item cgutl2vjy2ieoiyvhsfwtpryre --vault "UNSW" | jq -r '.details.fields[] | select(.designation=="password").value')" ssh z5384479@grieg.cse.unsw.edu.au
}

grieg


